version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


