version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development



  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  oceltotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

