version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5001:80"
    container_name: Catalog-API
    depends_on:
      - mongoProduct

  mongoProduct:
    image: mongo:latest
    ports:
      - "27018:27017"
    restart: always
 
    container_name: mongodProducts
    volumes: 
     - "./mongo-db-data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:localhost@mongo:27017/

    container_name: product-mongo


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
      - "5002:80"
      
    depends_on:
       - basket-cache

  basket-cache:
    image: "redis"
    # command: redis-server --save 20 1 --loglevel warning --requirepass RediIsLocalYo!
    ports:
     - "6380:6379" 
    container_name: basketRedisCache
    volumes: 
      - "./Redis-data:/data"
    restart: always
    

volumes:
  db-data:
